default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  username: <%= ENV.fetch("DB_USERNAME", "linear_clone") %>
  password: <%= ENV.fetch("DB_PASSWORD", "linear_clone_dev") %>

development:
  <<: *default
  database: linear_clone_development

test:
  <<: *default
  database: linear_clone_test

production:
  <<: *default
  database: linear_clone_production
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
