:concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", 10) %>
:timeout: 25
:queues:
  - [critical, 3]
  - [default, 2]
  - [mailers, 2]
  - [webhooks, 1]
  - [low, 1]

:scheduler:
  :enabled: true
  :dynamic: true
  :schedule:
    # notification_digest:
    #   cron: '0 9 * * *'  # Every day at 9am
    #   class: NotificationDigestJob
    #   queue: mailers
